Vagrant.configure("2") do |config|
  config.vm.box = "devbox"
  config.vm.box_url = "http://cloud-images.ubuntu.com/precise/current/precise-server-cloudimg-vagrant-amd64-disk1.box"
  config.vm.hostname = "devbox"

  config.vm.provision :puppet,:module_path => "puppet/modules" do |puppet|
     puppet.manifests_path = "puppet/manifests"
     puppet.manifest_file  = "site.pp"
  end
end
